version: "3.8"

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: spotifydb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  spotify-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spotify-api
    restart: always
    ports:
      - "5000:5000"
    working_dir: /app
    depends_on:
      - mysql-db
    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: spotifydb
      DB_PORT: 3306
      DB_DIALECT: mysql
      NODE_ENV: development

  spotify-frontend:
    build:
      context: ../cliente
      dockerfile: Dockerfile
    container_name: spotify-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - spotify-api
    environment:
      REACT_APP_API_URL: http://localhost:5000

volumes:
  mysql-data:
